### ISSUE TITLE
проблема с запуском из корня репозитория

### ISSUE THREAD

**Issue by wildzeliboba** [a01032004/LHW-documentation-for-competitions#11]
Есть трудности с запуском приложения из корня репозитория с помощью команды

```cmd
# при попытке запустить как скрипт
python3 main.py

# при попытке запустить как модуль
python3 -m main
```

**Comment by wildzeliboba** [comment]
```cmd
Traceback (most recent call last):
  File "/var/Shared/docs/практика/протоколы по лыжным гонкам/main.py", line 9, in <module>
    first_part = Participant(1, "First", 12, 26)
  File "/var/Shared/docs/практика/протоколы по лыжным гонкам/classes/Participant.py", line 34, in __init__
    self.factor = get_factor(self.sex, self.age)
  File "/var/Shared/docs/практика/протоколы по лыжным гонкам/calcs/utilites.py", line 23, in get_factor
    with open(path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '../calcs/man_factors.txt'
```

Явно беда с относительными путями

**Comment by wildzeliboba** [comment]
Так, беда также с запуском модуля `window.py` во внутреннем каталоге, т.к. при запуске в виде скрипта ломаются относительные пути, а в виде модуля - некорректное название каталога: тире не является допустимым для названия пакета элементом

Чёрт бы с ним, запустил, поправив название каталога

**Comment by Orbit-Boop** [comment]
При работе из консоли необходимо использовать python3 -m Interactive-window.window

Данное замечание описано в README
